NAPA.WebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NAPA.AppService;
using NAPA.Database;
using NAPA.Models;
using NAPA.ViewModels;

namespace NAPA.WebApp.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly IConfiguration configuration;

        public ProductsController(ApplicationContext context, IConfiguration _configuration)
        {
            _context = context;
            configuration = _configuration;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            InitializeTotalPrice();
            return View(await _context.Products.ToListAsync());
        }
        public void InitializeTotalPrice()
        {
            var products = _context.Products.ToList();
            double vat = double.Parse(configuration["VAT"]);
            foreach (var product in products)
            {
                product.TotalPrice = VAT.GetTotalPrice(product.Price, product.Quantity, vat);
            }
            _context.SaveChanges();
        }
        // GET: Products/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CreateProductVM viewModel)
        {
            if (ModelState.IsValid)
            {
                double vat = double.Parse(configuration["VAT"]);
                double price = double.Parse(viewModel.Price.Replace(".", ","));
                int quantity = viewModel.Quantity;
                Product product = new Product
                {
                    Name = viewModel.Name,
                    Price = price,
                    Quantity = quantity,
                    TotalPrice = VAT.GetTotalPrice(price, quantity, vat),
                    LastChangedDate = DateTime.Now.ToString("dd.MM.yyyy HH:mm")
                };
                _context.Add(product);
                int user_id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                await _context.SaveChangesAsync(user_id);
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            EditProductVM viewModel = new EditProductVM()
            {
                Id = id ?? 1,
                Quantity = product.Quantity,
                Price = product.Price.ToString(),
                Name = product.Name
            };
            return View(viewModel);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, EditProductVM viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    double vat = double.Parse(configuration["VAT"]);
                    double price = double.Parse(viewModel.Price.Replace(".", ","));
                    int quantity = viewModel.Quantity;
                    Product product = new Product
                    {
                        Id = id,
                        Name = viewModel.Name,
                        Price = price,
                        Quantity = viewModel.Quantity,
                        TotalPrice = VAT.GetTotalPrice(price, quantity, vat),
                        LastChangedDate = DateTime.Now.ToString("dd.MM.yyyy HH:mm")
                    };
                    _context.Update(product);
                    int user_id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                    await _context.SaveChangesAsync(user_id);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(viewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }


        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Bazada malumot yo'q");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }
            int user_id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            await _context.SaveChangesAsync(user_id);
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

NAPA.WebApp/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using NAPA.Models;
using NAPA.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace NAPA.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        RoleManager<Role> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<Role> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new Role { Name = name });
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            Role role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

NAPA.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NAPA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NAPA.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NAPA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    @if (Context.User.Identities.Any(i => i.IsAuthenticated))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item">
                                <a class="nav-link text-dark"  href="/swagger" >Web Api</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                               asp-action="ProductAudit">Product audit</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                               asp-action="AboutUsers">About users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products"
                               asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles"
                               asp-action="Index">Roles</a>
                            </li>
                            <li class="nav-item">
                                <form asp-action="Logout" asp-controller="Account" method="post">
                                    <button class="btn btn-danger" type="submit"><i class="bi bi-box-arrow-in-left"></i>Logout</button>
                                </form>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a class="btn btn-succes" asp-controller="Account"
                               asp-action="Register"><i class="bi bi-at"></i> Register</a>
                            </li>
                            <li>
                                <a class="btn btn-primary" asp-controller="Account"
                               asp-action="Login"><i class="bi bi-box-arrow-right"></i> Login</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NAPA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>